[package]
name = "termrender"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
once_cell = "1.21.3"
paste = "1.0.15"



[profile.minimal]
inherits = "release"     # Start from release settings
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
